### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by jeff-hiner**
@emberian We're ready for a release, if you want to merge this and then publish to crates.io.

### CODE REVIEW

**Comment by coolreader18** [comment]
Wait I've actually got another branch on my computer at home that adds a EventStream for raw_stream + optimizes the sync EventStream, I think I should be able to push it for review around 3 MT

**Comment by coolreader18** [comment]
Alright yeah I think it's good now

**Comment by jeff-hiner** [comment]
Hey @emberian, what's the next step getting this merged and released on crates.io?

**Comment by emberian** [comment]
@coolreader18 I've added you to the cargo owner list for this crate, and also will publish the new 0.11.0 version. apologies for the long wait!

**Comment by coolreader18** [comment]
@emberian thank you!

**Pull request merged**
