### PR TITLE
Fix build on 32 bit arm where tv_sec (time_t) is i32

### LINKED ISSUE #95: Build failure on 32 bit arm
See https://github.com/seanyoung/cir/issues/3#issuecomment-1222624442 :

```
   Compiling evdev v0.12.0
error[E0308]: mismatched types
   --> /home/keshlamIR/.cargo/registry/src/github.com-1285ae84e5963aae/evdev-0.12.0/src/lib.rs:393:29
    |
393 |     let dur = Duration::new(tv.tv_sec.unsigned_abs(), tv.tv_usec as u32 * 1000);
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^ expected `u64`, found `u32`
    |
help: you can convert a `u32` to a `u64`
    |
393 |     let dur = Duration::new(tv.tv_sec.unsigned_abs().into(), tv.tv_usec as u32 * 1000);
    |                                                     +++++++
```

On 32 bit arm `time_t` is an `i32`, see https://docs.rs/libc/latest/src/libc/unix/linux_like/linux/gnu/b64/mod.rs.html#20

### PR DESCRIPTION
**Pull request by seanyoung**
Fixes #95

### CODE REVIEW

**Review by coolreader18 — APPROVED** [review]

**Comment by coolreader18** [comment]
Thanks!

**Comment by CryZe** [comment]
Can we have a 0.12.1, this is apparently blocking me from upgrading.

**Comment by seanyoung** [comment]
I'm having the same problem too - a version `0.12.1` published on crates.io would really be appreciated. :pray:

**Comment by jonasfoyth** [comment]
Hello, some news about this new version? (0.12.1)

**Pull request merged**
